### ISSUE TITLE
resource_tracker.py:224 UserWarning: resource_tracker: There appear to be 1 leaked semaphore object to clean up at shutdown

### ISSUE THREAD

**Issue by tito2-lab** [OpenVINO-dev-contest/llama2.openvino#2]
Hello, 
when I run 
`$python3 export_ir.py -m 'meta-llama/Llama-2-7b-hf' -o './ir_model'`
I saw below error message: 

> Framework not specified. Using pt to export to ONNX.
> Killed
> /usr/lib/python3.10/multiprocessing/resource_tracker.py:224: UserWarning: resource_tracker: There appear to be 1 leaked semaphore objects to clean up at shutdown
>   warnings.warn('resource_tracker: There appear to be %d '

I'm using Ubuntu22.04 but on Windows11 WSL. 
Same error message can be shown on optimum-cli tool to convert.  
My resource is not enough to run this tool?

**Comment by OpenVINO-dev-contest** [comment]
Yes, you may need more than 128g RAM to export this model.

**Comment by tito2-lab** [comment]
Ok thanks.
